const ActionTypes = {
  INCREMENT: 'INCREMENT',
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  STORE_RESULT: 'STORE_RESULT',
  DELETE_RESULT: 'DELETE_RESULT'
}

export default ActionTypes;
